version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: heatmeup-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: heatmeup
    volumes:
      - ./docker/db-data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
